# Generated by Django 3.0.2 on 2020-01-17 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(help_text='category name,name must be unique', max_length=250, unique=True)),
                ('mobile_number', models.CharField(help_text='enter your mobile number', max_length=10)),
                ('booking_start_time', models.DateTimeField(auto_now_add=True, help_text='ride start time')),
                ('booking_end_time', models.DateTimeField(auto_now=True, help_text='ride end time')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(help_text='category name,name must be unique', max_length=250, unique=True)),
                ('mobile_number', models.CharField(help_text='enter your mobile number', max_length=10)),
                ('booking_start_time', models.DateTimeField(auto_now_add=True, help_text='ride start time')),
                ('booking_end_time', models.DateTimeField(auto_now=True, help_text='ride end time')),
            ],
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_start_time', models.DateTimeField(auto_now_add=True, help_text='ride start time')),
                ('booking_end_time', models.DateTimeField(auto_now=True, help_text='ride end time')),
                ('driver_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CabManagementApp.Driver')),
                ('user_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CabManagementApp.User')),
            ],
        ),
    ]
