# Generated by Django 3.0.2 on 2020-01-18 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CabManagementApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='ride_status',
            field=models.CharField(choices=[('1', 'ride_requested'), ('10', 'ride_accepted'), ('20', 'ride_done')], default='20', max_length=2),
        ),
        migrations.AlterField(
            model_name='ride',
            name='driver_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CabManagementApp.Driver'),
        ),
    ]
